# compile:
# 	@./cmd/compile.sh

# run:
# 	@./cmd/run.sh

compile:
	@mcs -out:./21_MethodParams/Program.exe ./21_MethodParams/Program.cs

run:
	@mono ./21_MethodParams/Program.exe

.PHONY: compile run